# Rock Paper Scissors image classifier

In [2]:
import tensorflow as tf
import numpy as np
from scipy.ndimage import zoom
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [3]:
training_dir = "rps/train/"
train_datagen = ImageDataGenerator(
    rescale = 1./255,
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

In [4]:
train_generator = train_datagen.flow_from_directory(
    training_dir,
    target_size=(150, 150),
    class_mode='categorical',
)

Found 2520 images belonging to 3 classes.


In [5]:
validation_dir = "rps/validation/"
validation_datagen = ImageDataGenerator(rescale = 1./255)
validation_generator = train_datagen.flow_from_directory(
    validation_dir,
    target_size=(150, 150),
    class_mode='categorical',
)

Found 33 images belonging to 3 classes.


In [6]:
test_dir = "rps/test/"
test_datagen = ImageDataGenerator(rescale = 1./255)
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(150, 150),
    class_mode='categorical',
    shuffle=False
)

Found 372 images belonging to 3 classes.


In [7]:
model = Sequential([
        Conv2D(64, (3, 3), activation='relu', input_shape=(150, 150, 3)),
        MaxPooling2D(pool_size=(2, 2)),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D(pool_size=(2, 2)),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D(pool_size=(2, 2)),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D(pool_size=(2, 2)),
        Flatten(),
        Dense(512, activation='relu'),
        Dense(3, activation='softmax')
])

C:\Users\sumes\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

In [9]:
history = model.fit(
    train_generator,
    epochs=15,
    validation_data=validation_generator,
)

79/79 ━━━━━━━━━━━━━━━━━━━━ 22s 276ms/step - accuracy: 0.9790 - loss: 0.0689 - val_accuracy: 0.8485 - val_loss: 0.5269


In [10]:
loss, acc = model.evaluate(test_generator)
print("Test accuracy:", acc)

Test accuracy: 0.9623655676841736


In [14]:
preds = model.predict(test_generator)
predicted_classes = (preds > 0.5).astype("int32")

print(predicted_classes[:10])  # first 10 predictions

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]]
